site_name: Pepperpy Poetry Plugin
site_description: Poetry plugin for managing shared configurations and templates
site_author: Felipe Pimentel
repo_url: https://github.com/felipepimentel/pepperpy-poetry
repo_name: felipepimentel/pepperpy-poetry

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quick-start.md
  - User Guide:
    - Examples: user-guide/examples.md
  - API Reference:
    - Overview: api/index.md
    - Configuration: api/config.md
    - Plugin: api/plugin.md
  - Contributing: contributing/index.md
